In [1]:
import pandas as pd
pd.set_option("display.max_rows", 100, "display.max_columns", 100)

In [5]:
PATH = 'D:/project/데이터 분석 프로젝트/이노포스트/data/'

df = pd.read_csv(PATH + '05_병의원/1. 병원정보서비스 2021.6.csv', encoding='cp949')

In [7]:
df.head(2)

,암호화YKIHO코드,요양기관명,종별코드,종별코드명,시도코드,시도코드명,시군구코드,시군구코드명,읍면동,우편번호,주소,전화번호,병원URL,개설일자,총의사수,의과일반의 인원수,의과인턴 인원수,의과레지던트 인원수,의과전문의 인원수,치과일반의 인원수,치과인턴 인원수,치과레지던트 인원수,치과전문의 인원수,한방일반의 인원수,한방인턴 인원수,한방레지던트 인원수,한방전문의 인원수,x좌표,y좌표
0,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,1,상급종합,220000,인천,220003,인천부평구,NaN,21431,인천광역시 부평구 동수로 56 (부평동),032-1544-9004,http://www.cmcism.or.kr/,1981-08-06,324,3,20,68,230,1,0,0,2,0,0,0,0,126.724899,37.484831
1,JDQ4MTYyMiM1MSMkMSMkNCMkODkkMzgxMzUxIzExIyQxIy...,강릉아산병원,1,상급종합,320000,강원,320100,강릉시,NaN,25440,강원도 강릉시 사천면 방동길 38 (),033-610-3114,http://www.gnah.co.kr,1996-07-30,203,1,0,41,159,0,0,0,2,0,0,0,0,128.857841,37.818433

In [9]:
df.shape

(74364, 29)

In [10]:
df.isnull().sum()

암호화YKIHO코드        0
요양기관명             0
종별코드              0
종별코드명             0
시도코드              0
시도코드명             0
시군구코드             0
시군구코드명            0
읍면동           43083
우편번호              0
주소                0
전화번호            309
병원URL         65265
개설일자             16
총의사수              0
의과일반의 인원수         0
의과인턴 인원수          0
의과레지던트 인원수        0
의과전문의 인원수         0
치과일반의 인원수         0
치과인턴 인원수          0
치과레지던트 인원수        0
치과전문의 인원수         0
한방일반의 인원수         0
한방인턴 인원수          0
한방레지던트 인원수        0
한방전문의 인원수         0
x좌표            3450
y좌표            3450
dtype: int64

In [32]:
df['시도코드명'].unique()

array(['인천', '강원', '서울', '대구', '경남', '경기', '충남', '부산', '전북', '광주', '대전',
       '충북', '울산', '전남', '경북', '세종시', '제주'], dtype=object)

In [31]:
# 대전 지역 데이터만 필터, `시도코드명` 에서 `대전`으로 대전 지역 데이터만 선별이 가능함
df1 = df.loc[df['시도코드명'] == '대전']
df1.head(2)

,암호화YKIHO코드,요양기관명,종별코드,종별코드명,시도코드,시도코드명,시군구코드,시군구코드명,읍면동,우편번호,주소,전화번호,병원URL,개설일자,총의사수,의과일반의 인원수,의과인턴 인원수,의과레지던트 인원수,의과전문의 인원수,치과일반의 인원수,치과인턴 인원수,치과레지던트 인원수,치과전문의 인원수,한방일반의 인원수,한방인턴 인원수,한방레지던트 인원수,한방전문의 인원수,x좌표,y좌표
34,JDQ4MTYyMiM2MSMkMSMkMiMkODkkMzgxMzUxIzExIyQxIy...,충남대학교병원,1,상급종합,250000,대전,250005,대전중구,NaN,35015,대전광역시 중구 문화로 282 (대사동),042-1599-7123,http://www.cnuh.co.kr/,1984-11-05,468,0,47,157,261,0,0,0,3,0,0,0,0,127.415363,36.316908
98,JDQ4MTYyMiM2MSMkMSMkMiMkODkkMzgxMzUxIzExIyQyIy...,근로복지공단 대전병원,11,종합병원,250000,대전,250002,대전대덕구,NaN,34384,대전광역시 대덕구 계족로 637 (법동),042-670-5419,NaN,1991-04-22,27,1,0,0,25,1,0,0,0,0,0,0,0,127.428549,36.368398

In [18]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2304 entries, 34 to 74334
Data columns (total 29 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   암호화YKIHO코드  2304 non-null   object
 1   요양기관명       2304 non-null   object
 2   종별코드        2304 non-null   int64
 3   종별코드명       2304 non-null   object
 4   시도코드        2304 non-null   int64
 5   시도코드명       2304 non-null   object
 6   시군구코드       2304 non-null   int64
 7   시군구코드명      2304 non-null   object
 8   읍면동         1205 non-null   object
 9   우편번호        2304 non-null   int64
 10  주소          2304 non-null   object
 11  전화번호        2299 non-null   object
 12  병원URL       289 non-null    object
 13  개설일자        2303 non-null   object
 14  총의사수        2304 non-null   int64
 15  의과일반의 인원수   2304 non-null   int64
 16  의과인턴 인원수    2304 non-null   int64
 17  의과레지던트 인원수  2304 non-null   int64
 18  의과전문의 인원수   2304 non-null   int64
 19  치과일반의 인원수   2304 non-null   int64
 20  치과인턴 인원수    2304 non-null   int64
 21  치과레지던트 인원수  2304 non-null   int64
 22  치과전문의 인원수   2304 non-null   int64
 23  한방일반의 인원수   2304 non-null   int64
 24  한방인턴 인원수    2304 non-null   int64
 25  한방레지던트 인원수  2304 non-null   int64
 26  한방전문의 인원수   2304 non-null   int64
 27  x좌표         2218 non-null   float64
 28  y좌표         2218 non-null   float64
dtypes: float64(2), int64(17), object(10)
memory usage: 540.0+ KB

In [37]:
# 1차 컬럼 삭제
df2 = df1.drop(['암호화YKIHO코드', # 불필요한 데이터
                '종별코드', # 불필요한 데이터
                '시도코드', # 불필요한 데이터
                '시도코드명', # 불필요한 데이터
                '시군구코드', # 불필요한 데이터
                '읍면동', # 불필요한 데이터
                '전화번호', # 불필요한 데이터
                '병원URL', # 불필요한 데이터
                '개설일자', # 불필요한 데이터
                '총의사수', # 불필요한 데이터
                '의과일반의 인원수', # 불필요한 데이터
                '의과인턴 인원수', # 불필요한 데이터
                '의과레지던트 인원수', # 불필요한 데이터
                '의과전문의 인원수', # 불필요한 데이터
                '치과일반의 인원수', # 불필요한 데이터
                '치과인턴 인원수', # 불필요한 데이터
                '치과레지던트 인원수', # 불필요한 데이터
                '치과전문의 인원수', # 불필요한 데이터
                '한방일반의 인원수', # 불필요한 데이터
                '한방인턴 인원수', # 불필요한 데이터
                '한방레지던트 인원수', # 불필요한 데이터
                '한방전문의 인원수' # 불필요한 데이터
                ], axis=1)

In [38]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2304 entries, 34 to 74334
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   요양기관명   2304 non-null   object
 1   종별코드명   2304 non-null   object
 2   시군구코드명  2304 non-null   object
 3   우편번호    2304 non-null   int64
 4   주소      2304 non-null   object
 5   x좌표     2218 non-null   float64
 6   y좌표     2218 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 144.0+ KB

In [39]:
df2.head()

,요양기관명,종별코드명,시군구코드명,우편번호,주소,x좌표,y좌표
34,충남대학교병원,상급종합,대전중구,35015,대전광역시 중구 문화로 282 (대사동),127.415363,36.316908
98,근로복지공단 대전병원,종합병원,대전대덕구,34384,대전광역시 대덕구 계족로 637 (법동),127.428549,36.368398
118,대전보훈병원,종합병원,대전대덕구,34314,대전광역시 대덕구 대청로82번길 147 147,127.439694,36.447316
119,대전한국병원,종합병원,대전동구,34572,대전광역시 동구 동서대로 1672 (성남동),NaN,NaN
121,대청병원,종합병원,대전서구,35403,대전광역시 서구 계백로 1322 (정림동),127.370584,36.308192

In [46]:
# 인덱스 재설정
df2.reset_index(drop=True)

,요양기관명,종별코드명,시군구코드명,우편번호,주소,x좌표,y좌표
0,충남대학교병원,상급종합,대전중구,35015,대전광역시 중구 문화로 282 (대사동),127.415363,36.316908
1,근로복지공단 대전병원,종합병원,대전대덕구,34384,대전광역시 대덕구 계족로 637 (법동),127.428549,36.368398
2,대전보훈병원,종합병원,대전대덕구,34314,대전광역시 대덕구 대청로82번길 147 147,127.439694,36.447316
3,대전한국병원,종합병원,대전동구,34572,대전광역시 동구 동서대로 1672 (성남동),NaN,NaN
4,대청병원,종합병원,대전서구,35403,대전광역시 서구 계백로 1322 (정림동),127.370584,36.308192
...,...,...,...,...,...,...,...
2299,회생한의원,한의원,대전서구,35210,"대전광역시 서구 월평동로 83 308,310호 (월평동, 다모아아파트상가)",127.366952,36.362287
2300,효자한의원,한의원,대전유성구,34230,대전광역시 유성구 진잠로42번길 117 (원내동),127.319935,36.298936
2301,후한의원,한의원,대전서구,35241,대전광역시 서구 둔산남로 101 (둔산동),127.388809,36.349260
2302,휴한의원,한의원,대전서구,35240,대전광역시 서구 둔산로123번길 15 (둔산동),127.387423,36.351993
2303,흑석한의원,한의원,대전중구,34976,대전광역시 중구 계백로 1554-1 1층 (유천동),127.392325,36.316849

In [47]:
df2.shape

(2304, 7)

CSV 파일로 저장

In [48]:
df2.to_csv(PATH + '05_병의원/병원정보서비스_전처리.csv', index=False, encoding='cp949')